<?php
$this->title = 'Liste des lots';
$this->headTitle($this->title);
?>

<table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
	<thead>
		<tr>
			<th>Lot Id</th>
			<th>Commande Id</th>
			<th>Nombre image</th>
		</tr>
    </thead>
	<tbody>
	</tbody>
</table>



<div id="info_pli" class="row">
<a style="" class="b-close">x</a>

<div class="content col-md-12" id ="content_info">
</div>
<div class="Action_button">
	<button class="btn btn-success" id="modif_lot">Modifier</button>
	
	<button class="btn btn-danger">Supprimer</button>
	<button class="btn btn-default " id="annul" style="display:none">Annuler</button>
	<button class="btn btn-primary" style="display:none" id="enreg">Enregistrer</button>
</div>

</div>